### PR TITLE
Export all datasets and filter by parameters

### LINKED ISSUE #2: Hard limit of 1000 rows
Even though the rows property is set to a high number in the code here, CKAN API has a hard limit of 1000 rows returned via the package_search action.

We may need to rework code to iterate through a number of times to return a full export.

See http://docs.ckan.org/en/latest/api/#ckan.logic.action.get.package_search

### PR DESCRIPTION
**Pull request by camfindlay**
Fixes #2 
Adds feature in #1 

Unsure who is maintaining this repo, happy to discuss further + peer review, merge and release to pip would be great!

TODO

- [x] Documentation update

### CODE REVIEW

**Comment by camfindlay** [comment]
I'm starting to tackle the passing of parameters into the export function as part of this PR which would make it a backwards compatible minor version (new feature).

**Comment by camfindlay** [comment]
@seanh are you/were you a maintainer on this repo?

**Comment by camfindlay** [comment]
Looking at the testing element it seems we'd be testing something executed in another library (the filtering in ckanapi). So I don't think we need to extend the tests further.

**Comment by amercader** [comment]
This looks good @camfindlay. I think you are the best candidate to maintain this repo from now on :) If you are happy I can give you admin perms here and on PyPI

**Comment by seanh** [comment]
Hi @camfindlay I wrote this a few years ago but there hasn't really been any maintenance to do and I haven't been using it (I no longer work for Open Knowledge or on CKAN). I think Adria has it right - feel free to take the repo over.

**Comment by camfindlay** [comment]
@amercader sure thing go ahead and add access 👍

**Comment by camfindlay** [comment]
@seanh add me as maintainer for this and I'll look to get new version on pypi asap 👍

**Comment by camfindlay** [comment]
@seanh ping :D keen to roll a new pypi version and tidy up gh issues. If you can add me as maintainer. C.

**Comment by boykoc** [comment]
@camfindlay for what it's worth I appreciate the updates you're making and also would like to see a new release with these changes.

**Comment by camfindlay** [comment]
Cheers @boykoc - I've been using anyway by installing from source code but a proper release would be nice. Just waiting to get some maintainer access action XD

**Comment by seanh** [comment]
@amercader Can you give @camfindlay admin perms here and on PyPI?

**Comment by amercader** [comment]
@camfindlay you are now a maintainer. Do you have an account on PyPI?

**Comment by camfindlay** [comment]
@amercader same as my GH username (camfindlay) :+1:

**Comment by amercader** [comment]
> User 'camfindlay' does not have a verified primary email address and cannot be added as a Maintainer for project.

@camfindlay ^

**Comment by camfindlay** [comment]
Try that now @amercader

**Comment by amercader** [comment]
@camfindlay Done, thanks for helping out!

**Comment by kannes** [comment]
It does not look like this was released via pypi yet?

**Comment by camfindlay** [comment]
@kannes minted a new release on pypi a couple of days ago. Thanks for the prompt :)

**Comment by kannes** [comment]
Excellent, thank you!

**Pull request merged**
